import {
  si1password,
  siAirtable,
  siApple,
  siApplemusic,
  siAppletv,
  siAsana,
  siAudible,
  siCalendly,
  siClaude,
  siCloudflare,
  siDatadog,
  siDigitalocean,
  siDiscord,
  siDropbox,
  siEvernote,
  siExpressvpn,
  siFigma,
  siGithub,
  siGodaddy,
  siGoogle,
  siGrammarly,
  siHbomax,
  siIcloud,
  siLinear,
  siMailchimp,
  siMedium,
  siMongodb,
  siNamecheap,
  siNetflix,
  siNordvpn,
  siNotion,
  siPatreon,
  siPlaystation,
  siPostman,
  siSentry,
  siShopify,
  siSpotify,
  siSquarespace,
  siSubstack,
  siTodoist,
  siTrello,
  siTwitch,
  siVercel,
  siWebflow,
  siWix,
  siYoutube,
  siYoutubemusic,
  siYoutubetv,
  siZapier,
  siZoom,
  type SimpleIcon,
} from "simple-icons";

// Ordered from most to least specific — e.g. "youtube music" must be
// checked before the generic "youtube" fallback. Only covers brands
// actually present in the simple-icons package: some major names (Amazon/
// AWS, Microsoft, LinkedIn, Disney+, Hulu, Adobe, Nintendo, Xbox, OpenAI,
// Canva, Slack) have been withdrawn from that library at the trademark
// holder's request, so those fall back to the plain colored-initial badge
// instead.
const BRAND_MATCHERS: { test: string; icon: SimpleIcon }[] = [
  { test: "youtube music", icon: siYoutubemusic },
  { test: "youtube tv", icon: siYoutubetv },
  { test: "youtube", icon: siYoutube },
  { test: "netflix", icon: siNetflix },
  { test: "spotify", icon: siSpotify },
  { test: "hbo", icon: siHbomax },
  { test: "apple music", icon: siApplemusic },
  { test: "apple tv", icon: siAppletv },
  { test: "icloud", icon: siIcloud },
  { test: "apple", icon: siApple },
  { test: "notion", icon: siNotion },
  { test: "figma", icon: siFigma },
  { test: "github", icon: siGithub },
  { test: "dropbox", icon: siDropbox },
  { test: "google", icon: siGoogle },
  { test: "zoom", icon: siZoom },
  { test: "discord", icon: siDiscord },
  { test: "twitch", icon: siTwitch },
  { test: "1password", icon: si1password },
  { test: "trello", icon: siTrello },
  { test: "asana", icon: siAsana },
  { test: "airtable", icon: siAirtable },
  { test: "linear", icon: siLinear },
  { test: "mailchimp", icon: siMailchimp },
  { test: "shopify", icon: siShopify },
  { test: "vercel", icon: siVercel },
  { test: "cloudflare", icon: siCloudflare },
  { test: "digitalocean", icon: siDigitalocean },
  { test: "mongodb", icon: siMongodb },
  { test: "postman", icon: siPostman },
  { test: "sentry", icon: siSentry },
  { test: "datadog", icon: siDatadog },
  { test: "webflow", icon: siWebflow },
  { test: "squarespace", icon: siSquarespace },
  { test: "wix", icon: siWix },
  { test: "godaddy", icon: siGodaddy },
  { test: "namecheap", icon: siNamecheap },
  { test: "nordvpn", icon: siNordvpn },
  { test: "expressvpn", icon: siExpressvpn },
  { test: "grammarly", icon: siGrammarly },
  { test: "evernote", icon: siEvernote },
  { test: "todoist", icon: siTodoist },
  { test: "medium", icon: siMedium },
  { test: "substack", icon: siSubstack },
  { test: "patreon", icon: siPatreon },
  { test: "audible", icon: siAudible },
  { test: "playstation", icon: siPlaystation },
  { test: "calendly", icon: siCalendly },
  { test: "zapier", icon: siZapier },
  { test: "claude", icon: siClaude },
  { test: "anthropic", icon: siClaude },
];

export function matchSubscriptionLogo(name: string): SimpleIcon | null {
  const normalized = name.trim().toLowerCase();
  if (!normalized) return null;
  const match = BRAND_MATCHERS.find(({ test }) => normalized.includes(test));
  return match?.icon ?? null;
}
